### PR TITLE
Rebuild config.yaml after make update-node-modules

### LINKED ISSUE #164: .build/config.yaml may not be up-to-date
After a `make update-node-modules` the closure utils library version number may have changed.
However, the `closure_library_path` in `.build/config.yaml` may not be up-to-date.

### PR DESCRIPTION
**Pull request by elemoine**
Fixes #164.

### CODE REVIEW

**Comment by pgiraud** [comment]
Looks good to me. I think it will need a rebase once the shapely version is fixed on master.

**Comment by sbrunner** [comment]
Does it relay do what we want ? 

Shouldn't we not simply remove the `.build/config.yaml` file ?

**Comment by elemoine** [comment]
> Shouldn't we not simply remove the .build/config.yaml file ?

We could just touch the `.build/node_modules.timestamp` file to indicate that `node_modules` was rebuilt, and make `.build/node_modules.timestamp` a dependency of `.build/config.yaml`.

New commit to come.

**Comment by elemoine** [comment]
I've changed the commit. @sbrunner does it make more sense to you?

**Comment by sbrunner** [comment]
Yes, relay better :-), merge when Travis is happy

**Pull request merged**
