### PR TITLE
Readding missing pyramid_closure settings

### LINKED ISSUE #184: debug mode doesn't work anymore
Restant c2c 01/02/2015 0.5j

----

I get the following error: `goog.require could not find: app.MainController`

`http://localhost:5000/closure-deps.js` returns an empty response.

### PR DESCRIPTION
**Pull request by pgiraud**
Fixes #184.

### CODE REVIEW

**Comment by pgiraud** [comment]
Please review.

**Comment by elemoine** [comment]
Please merge.

**Comment by sbrunner** [comment]
camptocamp/c2cgeoportal#1197, camptocamp/pyramid_closure#44 will be a better solution

**Comment by sbrunner** [comment]
Should be revert !

**Pull request merged**
