### PR TITLE
Mymaps design polishing

### PR DESCRIPTION
**Pull request by pgiraud**
With this pull request, I tried to improve the design of the mymaps block a bit.

Please review.

### CODE REVIEW

**Comment by jaykayone** [comment]
@rmichaelis can you make this testable for me please?

**Comment by rmichaelis** [comment]
done here devv3/renaud

**Comment by rmichaelis** [comment]
Maybe would it be better to have this PR rebased on the #924

**Comment by jaykayone** [comment]
yes that would be great

**Comment by pgiraud** [comment]
Hi, I rebased my pull request on to #924. Well actually it was too much work and did apply the changes manually.
I think that the usability is still not satisfying and I would really like to spend more time on it.
I won't be available this afternoon unfortunately.

**Comment by jaykayone** [comment]
​OK for you to spend more time on it next week, if that fits your planning

**Comment by pgiraud** [comment]
I rebased the pull request. You can test it and merge it if it looks OK to you.
I think there's a need for user testing sometimes later.

**Comment by rmichaelis** [comment]
You can test it here http://devv3.geoportail.lu/renaud/

**Comment by rmichaelis** [comment]
Problem when too many elements are part of the map. Maybe a scrollbar is needed ?

image

**Comment by jaykayone** [comment]
is it the same icon for every type of geometry?

**Comment by jaykayone** [comment]
there is a usability problem on mobile.
the interaction between list and maps is not easy to understand because sidepanel is fullscreen

**Comment by jaykayone** [comment]
http://devv3.geoportail.lu/renaud/theme/main?version=3&zoom=10&X=668083&Y=6405320&lang=de&bgLayer=basemap_2015_global&layers&opacities&map_id=67b9be9ae3f947be95968e76c6dfc713 

I cannot select the elements on the map, only in the list ..

**Comment by pgiraud** [comment]
> is it the same icon for every type of geometry?

The icons are not part of the current pull request. This is part of a new one which is still in progress. See #940.

**Comment by pgiraud** [comment]
> I cannot select the elements on the map, only in the list ..

This issue doesn't seem to be introduced by the current pull request. The problem also appears with `master` branch. Opening a new issue.

**Comment by pgiraud** [comment]
> Problem when too many elements are part of the map. Maybe a scrollbar is needed ?

Issue addressed in my last commit.

**Comment by pgiraud** [comment]
I think that the usability issue need to be addressed in a separate issue.
Please review.

**Comment by pgiraud** [comment]
I rebased this pull request. Can we merge it (when Travis is happy)?

**Comment by geoportallux** [comment]
OK for me /jk

**Pull request merged**
