### PR TITLE
Add layer manager

### PR DESCRIPTION
**Pull request by elemoine**
This a new PR for @pgiraud's `layer_manager` branch. For some reason @pgiraud's PR #142 didn't land into `master`, although the PR did have `master` as the target/base branch.

This is what I used to rebase the `layer_manager` onto the current `origin/master` branch:

```
$ git fetch origin
$ git checkout --no-track -b layer_manager origin/layer_manage  # create a local "layer_manager" branch off "origin/layer_manager"
$ git rebase --onto origin/master 77fe4a4  # 77fe4a4 is the first commit of "layer_manager" that I don't want (that is not part of Pierre's work)
$ git push --force origin layer_manager
```

And I then create that PR, using `master` as the "base" branch, and `layer_manager` as the "head" branch. I'm going to merge this. If it does not work, that means our GitHub repo is broken/corrupted.

### CODE REVIEW

**Comment by elemoine** [comment]
The merge worked as expected. Good news is our GitHub repo is not broken. Bad news: someone is doing bad things with Git :-)

**Comment by petzlux** [comment]
😬

**Comment by jaykayone** [comment]
As discussed on tuesday, I wanted to test this.
It seems that it only works in debug mode.
Otherwise the layermanager seems ok. I think the interaction between the eye and the slider (http://www.deezer.com/track/576431) does not match the discussion and conclusions we had here though.

As for the update you mentioned to the catalog, so that it works better with multi-level groupings, I suppose it is not merged yet

**Comment by pgiraud** [comment]
You meant : https://github.com/Geoportail-Luxembourg/geoportailv3/issues/13

**Comment by jaykayone** [comment]
yes

**Pull request merged**
