### PR TITLE
Update of translations

### PR DESCRIPTION
**Pull request by petzlux**

### CODE REVIEW

**Comment by jaykayone** [comment]
don't merge, there are wrong translations

**Comment by petzlux** [comment]
@jaykayone better ?

**Comment by jaykayone** [comment]
a little bit

**Comment by petzlux** [comment]
@pgiraud @elemoine  

The translations for the measure tools tooltips are not taken into account. They are present in the .po files, but missing from the generated geoportailv3.json language files and thus the tooltips are always in english.

**Comment by elemoine** [comment]
> The translations for the measure tools tooltips are not taken into account. They are present in the .po files, but missing from the generated geoportailv3.json language files and thus the tooltips are always in english. 

@petzlux did you remove that comment?

**Comment by jaykayone** [comment]
good question ;)

**Comment by petzlux** [comment]
Yes I did, somehow a rebuild did the trick , probably my stupidity rather than a real problem.

**Comment by jaykayone** [comment]
let's merge

**Pull request merged**
