### PR TITLE
Don't fail if geometry is used instead of bbox

### LINKED ISSUE #1504: search is broken
http://apps.geoportail.lu/exemple_api/apiv3_demo.html

### PR DESCRIPTION
**Pull request by pgiraud**
Fixes #1504.

I can't really test this on my side. @jaykayone Can you please give this branch a try?

### CODE REVIEW

**Comment by jaykayone** [comment]
hi, I've switched to that branch but without success

**Comment by jaykayone** [comment]
when I build that branch, the entire apiloader does not work anymore ...
might be my fault though ...

**Comment by pgiraud** [comment]
I just checked out this branch and I get the loader working as expected.
Can you please make sure your git folder is clean? You can try a "reset --hard" to make sure you get the same history as the remote.

**Comment by jaykayone** [comment]
I don't know why, but it does not work:

http://apiv3.geoportail.lu/apiv3loader.js

there is nothing in the logs

**Comment by jaykayone** [comment]
OK now i see ... this branch is not in our repo but in a fork ... but I already had a branch with the same name

**Comment by jaykayone** [comment]
now i am on your branch, but the search does not work ..

f.join() is not a function

**Comment by pgiraud** [comment]
What's the URL of your demo?

**Comment by jaykayone** [comment]
http://apps.geoportail.lu/exemple_api/apiv3_demo.html

**Comment by pgiraud** [comment]
I'm not an expert at reading obfuscated javascript code, but the following make me think that your build doesn't include the modifications provided in the current pull request.
screenshot from 2016-10-14 14 27 02

There's no `getExtent`.

**Comment by jaykayone** [comment]
OK, I am doing a cleanall right now, we'll see

**Comment by jaykayone** [comment]
I built it again and still have the same problem ..

```
[root@workshop3-local apiv3]# git status
# On branch pgiraud/jsapi_search_fix
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#      	modified:   apache/wsgi.conf.mako
#      	modified:   geoportailv3/locale/de/LC_MESSAGES/geoportailv3-server.po
#      	modified:   geoportailv3/locale/en/LC_MESSAGES/geoportailv3-server.po
#      	modified:   geoportailv3/locale/fr/LC_MESSAGES/geoportailv3-server.po
#      	modified:   geoportailv3/locale/lb/LC_MESSAGES/geoportailv3-server.po
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#      	=0a
#      	=1.1.0
#      	apache/geoportailv3.wsgi
#      	apache/geoportailv3.wsgi.mako
#      	api.mk
#      	conf/
#      	geoportailv3/ParcelDetailVer1Service
#      	geoportailv3/ParcelDetailVer1Service.wsdl
#      	vars_api.yaml
no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by pgiraud** [comment]
Can you edit the "jsapi/src/main.js" file and make sure the code contains the modifications?

**Comment by jaykayone** [comment]
you are right, it does not:

```
    var geom = /** @type {ol.geom.Point} */ (format.readGeometry(item.geometry));
      var bbox = (!item.bbox.join) ? geom : item.bbox;
      return '<div class="autocomplete-suggestion" data-val="' + label + '"' +
          'data-coord="' + geom.getCoordinates().join(',') + '"' +
          'data-extent="' + bbox.join(',') + '">' +
          label.replace(re, '<b>$1</b>') +
          '</div>';
```

doing it manually now

**Comment by jaykayone** [comment]
OK, it works now

**Comment by pgiraud** [comment]
@jaykayone Do you approve this pull request? Can it be merged?

**Pull request merged**
