### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by fredj**
Update project dependencies (angular, OpenLayers and ngeo).

todo:
 - [x] Profile does not work anymore.
 - [x] Point Drawing : Selection of the "width" using the range selector does not allow to select the entire range.
 - [x] Unable to login despite the fact that the login webservice returns true.
 - [x] Layer information does not work.
 - [ ] check if the image upload works
 - [x] Use `constraintResolution` option in `MouseWheelZoom` and `PinchZoom`
 - [x] Fix tooltip styling (measure) -> add missing `ngeo-` prefix to css class
 - [x] Remove step attribute from input number (style editing)
 - [x] Print symbol
 - [ ] input number when the step is not 1

### CODE REVIEW

**Comment by rmichaelis** [comment]
Profile does not work anymore.

**Comment by rmichaelis** [comment]
Point Drawing : Selection of the "width" using the range selector does not allow to select the entire range.

**Comment by rmichaelis** [comment]
Unable to login despite the fact that the login webservice returns true.

**Comment by rmichaelis** [comment]
Layer information does not work.

**Comment by fredj** [comment]
@rmichaelis the callback name should be fixed now

**Comment by rmichaelis** [comment]
It works now. Thanks.

**Comment by fredj** [comment]
@rmichaelis the login and the vector style update should be fixed now, can you please test?

**Comment by rmichaelis** [comment]
It looks fine.

**Comment by rmichaelis** [comment]
@fredj The last commit seems to solve the remaining issues.  Are you ready with this PR ? 
@jaykayone could you have a try on devv3/renaud  ?

**Comment by jaykayone** [comment]
on macintosh I saw that when i scroll with the mouse, it zooms seemlessly between the fixed tile scales, which has the effect that the scale bar shows an empty value:

screen shot 2017-04-04 at 15 20 44

**Comment by rmichaelis** [comment]
Background color of the area was better in the old version:
New measurement tool
image
Old measurement tool
image

**Comment by rmichaelis** [comment]
Unable to write the number using the keyboard. 
The granularity should not be the same in the text area as in the selector.
image

**Comment by fredj** [comment]
I've updated this ticket description with your remarks, you are very good testers BTW :-)

**Comment by rmichaelis** [comment]
Printting a symbol does not work anymore.
"graphicFormat" seems to be lost in the symbolizers attribute.
image
image

**Comment by fredj** [comment]
@rmichaelis for the print issue:
It's not working when an image symbol is used, and it's working when a shape (circle, square, triangle, ...) is used, can you confirm?

Maybe the issue is that the print can't access devv3/renaud (mapfish print dnsMatch config ?)

**Comment by rmichaelis** [comment]
Yes its working with shape and not with symbols. 
You can test here : http://g-o.lu/3/RLaJ

The problem comes frome here :
https://github.com/camptocamp/ngeo/commit/a57a08364674732b4ca763c367ae43dda8965d7f

If the graphicFormat is not provided, map fish print is not working.
map fish print works fine even if the provided type is not the real one.

**Comment by fredj** [comment]
@rmichaelis I've updated this PR, all the mentioned issues should be fixed now. Can you please update devv3/renaud and test again?

**Comment by rmichaelis** [comment]
devv3/renaud is updated. It seems to be ok. Except this: Arrows are not working.
image

@jaykayone : could you please try ?

**Comment by fredj** [comment]
The arrows are not working if the step of the corresponding slider is not 1

**Comment by fredj** [comment]
The problem is that when the arrow is clicked, the value is incremented by 1 and the setter function is correctly called (50 to 51).

Then, the value is set to the slider but since the step is 5 instead of 1, the value is set back to the original (51 to 50).

We will have to remove the step from the slider or add the same step to the number input

**Comment by rmichaelis** [comment]
Try to select a drawing on the map, returns this error : 

`querydirective.js:466 Uncaught TypeError: Cannot read property 'getArray' of undefined
    at querydirective.js:466
    at forEachFeatureAtCoordinate (map.js:120)
    at vectorlayer.js:199
    at replaygroup.js:234
    at ol.render.canvas.PolygonReplay.ol.render.canvas.Replay.replay_ (replay.js:419)
    at ol.render.canvas.PolygonReplay.ol.render.canvas.Replay.replayHitDetection (replay.js:568)
    at ol.render.canvas.ReplayGroup.replayHitDetection_ (replaygroup.js:369)
    at ol.render.canvas.ReplayGroup.forEachFeatureAtCoordinate (replaygroup.js:222)
    at ol.renderer.canvas.VectorLayer.forEachFeatureAtCoordinate (vectorlayer.js:189)
    at ol.renderer.canvas.Map.ol.renderer.Map.forEachFeatureAtCoordinate (map.js:147)`

**Comment by fredj** [comment]
> Try to select a drawing on the map, returns this error ...

fixed with c8b2f3d

**Comment by rmichaelis** [comment]
It works fine. Thanks.

**Comment by rmichaelis** [comment]
@fredj We would like to merge this pull request.
Could you please rebase ? If needed, I'll solve the step problems by myself.

**Comment by fredj** [comment]
@rmichaelis code rebased.
Feel free to merge, one solution (untested) to fix the step issue is to revert this commit: cbb63c3

**Comment by rmichaelis** [comment]
@fredj Thanks for the work.

**Pull request merged**
