### PR TITLE
Retina tiles support for background layers

### LINKED ISSUE #1124: retina tiles for basemap
cf http://apps.geoportail.lu/exemple_api/wmts_demo_ol3_retina.html

### PR DESCRIPTION
**Pull request by petzlux**
_hd tiles are loaded if metadata property hasRetina is true AND device has retina screen

fix #1124

### CODE REVIEW

**Comment by petzlux** [comment]
@jaykayone can you put this branch on beta.geoportail.lu so that we can test on mobile devices

**Comment by petzlux** [comment]
have asked here for some guidance on retina tiles in mapfish-print https://github.com/mapfish/mapfish-print/issues/478

**Comment by jaykayone** [comment]
we could also simply print the non retina ones

**Comment by petzlux** [comment]
@jaykayone exactly!

**Comment by jaykayone** [comment]
as e print at 127 dpi, there will be no gain in using retina tiles

**Comment by petzlux** [comment]
@jaykayone  LGTM ?

**Comment by jaykayone** [comment]
@rmichaelis can you already review the code so that we can merge as soon as the seeding is done?

**Pull request merged**
