### PR TITLE
no scrollbar

### PR DESCRIPTION
**Pull request by rmichaelis**
Please review

### CODE REVIEW

**Comment by rmichaelis** [comment]
fixes #623

**Comment by petzlux** [comment]
LGTM !

**Comment by pgiraud** [comment]
It looks like a hack to me.
But anyway, feel free to merge.

**Comment by rmichaelis** [comment]
@pgiraud do you prefer this new solution ?

**Comment by pgiraud** [comment]
It looks better to me.
I hope it doesn't break anything else though.

**Pull request merged**
