### PR TITLE
Upgrade c2cgeoportal version

### PR DESCRIPTION
**Pull request by sbrunner**
Update to new version of c2cgeoportal,

One important change is that we merge the geoportailv3.pot and the geoportailv3-db.pot into one single file named geoportailv3-client.pot, => same for po files.

### CODE REVIEW

**Comment by sbrunner** [comment]
Related to camptocamp/c2cgeoportal#1174

**Comment by sbrunner** [comment]
The Travis error will be fixed when the c2cgeoportal will be merged :-)

**Comment by elemoine** [comment]
Quick question: why did you move the less files into the `static` dir?

**Comment by sbrunner** [comment]
Because all the client specific files are in the static folder static, for me it's relay strange to see those files here, where these is only files directly related to do the build or relay separate features like the the print, the deploy and mapserver ...

**Comment by elemoine** [comment]
I understand. At the same time it is also strange and confusing to place in the `static` dir files that are not static resources (i.e served by the application as static assets). How about using `geoportailv3/less`?

**Comment by sbrunner** [comment]
less files are dynamic files ?
why is it reals a goal to hide those files ?
and if one time we want to use a library like http://lesscss.org/#download-options to use the less files in the browser we should move them in the static folder ... ?
For those reason for me the best place is in the static folder...

**Comment by petzlux** [comment]
Where did the db_to_pot helper function go ? I can see a call to a command db2po now, but not the function ?

**Comment by sbrunner** [comment]
@petzlux to the c2cgeoportal project: https://github.com/camptocamp/c2cgeoportal/pull/1174/files#diff-67

**Comment by petzlux** [comment]
Okay ! Thanks

**Comment by elemoine** [comment]
I am not opposed to place the less files in the `static` folder.

**Comment by petzlux** [comment]
Before this PR is merged, can we make sure that Transifex project will be updated, as we changed the .pot/.po file structure !

**Pull request merged**
