### PR TITLE
Petzlux search migrate 5.2

### PR DESCRIPTION
**Pull request by petzlux**

### CODE REVIEW

**Comment by petzlux** [comment]
@rmichaelis review  ?

**Comment by rmichaelis** [comment]
Try this : search for "Grundwasser [Nitratrichtlinie]" and select it.
It returns an error in console.

**Comment by petzlux** [comment]
Nope no error for me?

**Comment by rmichaelis** [comment]
"pénurie eau potable" does not show anymore "Open in theme Water" Is this wanted ?

**Comment by rmichaelis** [comment]
```
angular.js:13920 TypeError: Cannot use 'in' operator to search for 'type' in null
    at app.SearchDirectiveController.getLayerForCatalogNode [as getLayerFunc_] (layerfactoryservice.js:201)
    at app.SearchDirectiveController.addLayerToMap_ (searchdirective.js:839)
    at app.SearchDirectiveController.selected_ (searchdirective.js:902)
    at search.js:94
    at Scope.$eval (angular.js:17682)
    at Scope.$apply (angular.js:17782)
    at HTMLInputElement.<anonymous> (search.js:93)
    at HTMLInputElement.dispatch (jquery.js:4737)
    at HTMLInputElement.elemData.handle (jquery.js:4549)
    at Object.trigger (jquery.js:7807)
```

**Pull request merged**
