### PR TITLE
Layer exclusions updates (translation and layer removal)

### PR DESCRIPTION
**Pull request by pgiraud**
Please review.

@jaykayone I'm not sure the messages are clear enough. The messages could probably be shorter and more explicit.
Also though this exclusion notification mechanism improves usability, I'm still not sure users understand immediately what happens. At least, they are notified.

### CODE REVIEW

**Comment by jaykayone** [comment]
The messages are OK for me. They could stay a bit longer.
But there is a functional problem:
- Activate cadastral parcels -> background disappears (with notification) (OK)
- reactivate background -> parcels disappear (with notification) (OK)

BUT: 
- checkbox of cadastral parcels stays
AND:
- no possibility to re-display cadastral parcels from that moment on

**Comment by pgiraud** [comment]
Actually the "cadastral parcels" layer is still in the selected layers but it's opacity is set to 0. Is it not the expected behavior?

**Comment by jaykayone** [comment]
OK I see. In that case, the icon with the eye should be visible in the catalog and in the non-collapsed part of the layer in the layer manager, otherwise people will not understand what's going on.
If we don't want to change the interface, I'd suggest to remove the layer rather than deactivating it

**Comment by pgiraud** [comment]
OK.

We may also want to inform that the layer opacity is set to 0 without expanding the layer actions by for example modify the visual aspect.

**Comment by jaykayone** [comment]
My short experience shows me that people tend to stay in the catalog view rather than switching to my_layers (unless they want to reorder or change transparency). so they should also see inside the catalog when a layer is deactivated (maybe a grey checkbox and an additional click brings it back). Sort of a 3-state-checkbox?

**Comment by pgiraud** [comment]
OK. I updated the code so that the layers are removed when not compatible with newly chosen background. This is indeed a more natural behavior.

**Comment by jaykayone** [comment]
closes #379

**Pull request merged**
