### PR TITLE
Misc changes

### PR DESCRIPTION
**Pull request by elemoine**
This PR makes minor changes to the JS code. It also adds libldap2-dev and libsasl2-dev as requirements in the README file (I don't know how the equivalent RedHat packages are named).

### CODE REVIEW

**Comment by elemoine** [comment]
@jaykayone, do you know the equivalent RedHat packages for `libsasl2-dev` and `libldap2-dev`? Thanks.

**Comment by jaykayone** [comment]
@rmichaelis ?

**Comment by rmichaelis** [comment]
Not sure about the package names. 
But what I did is : 
a. Yum install openldap-devel
b. Pip install python-ldap
c. Pip install pyramid_ldap

**Comment by elemoine** [comment]
> a. Yum install openldap-devel

This is the one I was looking for. And nothing for `sasl`? On my side I had to install the `libsasl2-dev` package on my Ubuntu laptop.

**Comment by rmichaelis** [comment]
No, nothing else.

**Comment by elemoine** [comment]
Thanks.

I changed the README. I'll merge this if there's no other comments.

**Pull request merged**
