### PR TITLE
Use typeahead.js 0.11.1

### PR DESCRIPTION
**Pull request by elemoine**
We're [updating](https://github.com/camptocamp/ngeo/pull/283) ngeo with version 0.11.1 of typeahead.js. This PR accommodates this update.

Please review and test.

When reviewed and tested I'll merge https://github.com/camptocamp/ngeo/pull/283 and this PR.

### CODE REVIEW

**Comment by elemoine** [comment]
@petzlux, could you please test this?

**Comment by petzlux** [comment]
@elemoine sorry but after a `make -f wepa.mk clean update-node-modules serve` the search does not display results from the `fulltextsearch.py` service. Results are coming back tough.

**Comment by elemoine** [comment]
Strange. What if you do a local search (layers)? Is your instance available on devv3 so I can test it myself? Thanks for testing.

**Comment by elemoine** [comment]
I need to merge https://github.com/camptocamp/ngeo/pull/283 as soon as possible, as other projects need it. @petzlux, can I merge https://github.com/camptocamp/ngeo/pull/283 and this PR? We can address the remaining issues together when this is merged.

**Comment by elemoine** [comment]
I'll obviously remove the last commit before merging.

**Comment by petzlux** [comment]
@elemoine 
http://devv3.geoportail.lu/renaud/theme/main?version=3&zoom=16&X=693049&Y=6395421&lang=lb&layers&opacities&bgLayer=orthogr_2013_global&debug=true

Here you can see the behaviour, only if there is a single result does the poi/adress search result get displayed.

Hope this helps

**Comment by elemoine** [comment]
It does help.

I think we're hitting by https://github.com/twitter/typeahead.js/pull/1319. I'll try to provide a workaround.

**Comment by elemoine** [comment]
I added a workaround that should fix it. Could you please test again?

**Comment by elemoine** [comment]
Have you been able to verify that 7ca21c0 fixes the problem? May I merge this.

**Comment by petzlux** [comment]
@elemoine Yes works now !
http://devv3.geoportail.lu/renaud/theme/main?version=3&zoom=16&X=695471&Y=6395497&lang=lb&layers&opacities&bgLayer=orthogr_2013_global

**Comment by elemoine** [comment]
Cool. I am going to merge https://github.com/camptocamp/ngeo/pull/283, and rebase this PR and merge it. Thanks again for testing.

**Pull request merged**
