### PR TITLE
Search for Coordinates

### LINKED ISSUE #492: Search field - support coordinates entry

### PR DESCRIPTION
**Pull request by petzlux**
As requested by @jaykayone , users can enter LUREF coordinates in search field to go to specified location

fixes #492

### CODE REVIEW

**Comment by jaykayone** [comment]
btw: the same should work for ll84 lat,lon

**Comment by petzlux** [comment]
@elemoine  what is best way to retrieve from this.map the zoom constraints bbox  ? There doesnt seem to be a .getExtent() method on [ol.View](http://openlayers.org/en/v3.5.0/apidoc/ol.View.html) 

I would want to check if search coordinates are within [bounding box defined in our project](https://github.com/Geoportail-Luxembourg/geoportailv3/pull/341/files#diff-2a25edf714e2cafa32de6cc6e1c8cbf9R132)

**Comment by petzlux** [comment]
@jaykayone in what format ?

**Comment by jaykayone** [comment]
in geoportailv2, we got this format supported: 6.1298 49.6041

**Comment by elemoine** [comment]
@petzlux, we could define the constraining extent as an Angular constant, and then inject that constant where we need it.

For example, we can the following to `appmodule.js`:

```js
goog.require('ol.proj');

app.module.constant('appMaxExtent',
    ol.proj.transformExtent([2.6, 47.7, 8.6, 51], 'EPSG:4326', 'EPSG:3857'));
```

and then we can inject and use `appMaxExtent` wherever we need it.

Would that work for you?

**Comment by petzlux** [comment]
@elemoine Makes sense

just to be clear, in ol3, there is currently no method to get the view constraining extent once initialised ?

**Comment by elemoine** [comment]
> just to be clear, in ol3, there is currently no method to get the view constraining extent once initialised ?

No there isn't. The user is responsible for keeping a reference to that extent if using it elsewhere is necessary.

Also, note that I used `ol.proj.transformExtent` in my code example.

**Comment by petzlux** [comment]
Review please !

**Comment by sbrunner** [comment]
@elemoine this pull request add a new external library, do we as add it to c2cgeoportal, or is it a dependency that we will not have in c2cgeoportal and we should add a way do add it only in the project ?

**Comment by elemoine** [comment]
@sbrunner, I guess you're talking about Fuse in #503?

**Comment by petzlux** [comment]
@elemoine  any further comments on this pull request, or good to merge once travis is happy ?

**Comment by elemoine** [comment]
ok to me.

**Comment by petzlux** [comment]
:+1:

**Comment by sbrunner** [comment]
@elemoine oups sorry I mix my tabs :-(

**Pull request merged**
