### PR TITLE
Delete vertice using SHIFT key

### LINKED ISSUE #989: delete vertex
no possibility yet to delete vertex?

### PR DESCRIPTION
**Pull request by rmichaelis**
fixes #989

### CODE REVIEW

**Comment by rmichaelis** [comment]
@jaykayone is SHIFT key okay for you  ?

**Comment by jaykayone** [comment]
after doing some user tests, the conclusion is:

there should be two possibilities:
- "Click on point and hit DELETE"
- Right click on point and click "DELETE" in menu (cf google mymaps)

**Comment by pgiraud** [comment]
By default in OL3, if you single click on the vertex it is removed. This option has been deactivated in geoportailV3.
Isn't it a good solution before we get a contextmenu?

**Comment by jaykayone** [comment]
yes this can be a good compromise for not to be blocked

**Comment by pgiraud** [comment]
In this case, @rmichaelis you should completely remove the `deleteCondition`.

**Comment by pgiraud** [comment]
FYI, I started to give the contextmenu a try in an isolated OL3 example.

**Comment by rmichaelis** [comment]
Unfortunately, It's not so easy :-)
Removing the ```deletecondition``` throws unwanted event. 
The modify event is directly thraws after the create event.
That's the reason why we explicitly deactivated the default behaviour.

**Comment by jaykayone** [comment]
+1 for the example

**Pull request merged**
