### PR TITLE
Add support for A2, A1, and A0 print-outs

### PR DESCRIPTION
**Pull request by elemoine**
Fixes https://github.com/Geoportail-Luxembourg/geoportailv3/issues/468.

Please review.

### CODE REVIEW

**Comment by pgiraud** [comment]
Looks good. Please merge.

**Comment by sbrunner** [comment]
All throes values should be get from the print capabilities ... not ?

**Comment by elemoine** [comment]
Yes, eventually. At this point the ngeo print service [does not support](https://github.com/camptocamp/ngeo/blob/8babd0613aece4f2dd571a2ce7f8253dfa410987/src/services/print.js#L25) getting the print capabilities from MapFish Print. So the print configuration is duplicated.

**Comment by sbrunner** [comment]
OK, thanks for the additional information :-)

**Pull request merged**
