### PR TITLE
Add theme rewrite rules

### PR DESCRIPTION
**Pull request by sbrunner**
Add a rewrite rule for all the themes, I get all the available themes but probably most of them should be removed...

Related to #404

### CODE REVIEW

**Comment by jaykayone** [comment]
shouldn't the themes come directly from db instead of saving them in the yaml file?

**Comment by sbrunner** [comment]
Why not but it should be made and takes some time probably 1-2 days

**Comment by jaykayone** [comment]
/wsgi/theme/{theme} will always work?
It's only for /wsgi/{theme} that we need this, right?

In that case I can do all the rest with rewrites on the reverse proxy, so no need for further developments here

**Comment by sbrunner** [comment]
yes, yes, exactly :-)

**Comment by elemoine** [comment]
@jaykayone, yes, we thought it would be best to handle `/wsgi/{theme}` requests with an Apache rewrite rule. Please close this issue if the Lux team takes care of that.

**Comment by jaykayone** [comment]
ok if this works http://devv3.geoportail.lu/main/wsgi/test (which is not the case today) we can take care of the rest 

but we have to be careful to support the old permalinks correctly

to be tested

**Comment by jaykayone** [comment]
sorry I meant http://devv3.geoportail.lu/main/wsgi/theme/test

**Pull request closed without merging**
