### PR TITLE
Adding a make target to automatically build less files

### PR DESCRIPTION
**Pull request by pgiraud**

### CODE REVIEW

**Comment by pgiraud** [comment]
This pull request doesn't have any influence on the project itself. Merging.

**Comment by elemoine** [comment]
Is `watchmedo` better than `nosier`?

**Comment by pgiraud** [comment]
For an unknown reason, nosier refused to work properly today. I decided to find a less old package to do the same.

**Comment by elemoine** [comment]
Ok thanks.

**Pull request merged**
