### PR TITLE
Use our own CreateGeoJSONBloodhound factory

### PR DESCRIPTION
**Pull request by elemoine**
This PR should fix the remaining search problems we have.

@rmichaelis, can you please test this?

### CODE REVIEW

**Comment by rmichaelis** [comment]
Results are now returned but the centering on the selected feature is not working properly.
image

**Comment by elemoine** [comment]
> Results are now returned but the centering on the selected feature is not working properly.

Thanks for testing. What's the problem exactly?

**Comment by rmichaelis** [comment]
I my example the feature should be displayed here 6.112554342579504 , 49.6106117525195
but it's displayed here 0.00006 0.00049

**Comment by elemoine** [comment]
Strange. Do you have the same problem in debug mode?

**Comment by rmichaelis** [comment]
Yes I have the same problem in debug mode. 
I've just executed a clean but the problem is still remaining.

**Comment by elemoine** [comment]
Ok thanks.

Could you please try this patch?

```diff
diff --git a/geoportailv3/static/js/search/searchdirective.js b/geoportailv3/static/js/search/searchdirective.js
index e5d680d..d3b9726 100644
--- a/geoportailv3/static/js/search/searchdirective.js
+++ b/geoportailv3/static/js/search/searchdirective.js
@@ -529,7 +529,7 @@ app.SearchDirectiveController.prototype.createAndInitPOIBloodhound_ =
     function(appCreateGeoJSONBloodhound, searchServiceUrl) {
   var url = searchServiceUrl + '?limit=5&query=%QUERY';
   var bloodhound = appCreateGeoJSONBloodhound(
-      url, undefined, ol.proj.get('EPSG:3857'));
+      url, ol.proj.get('EPSG:3857'));
   bloodhound.initialize();
   return bloodhound;
 };
```

(The problem may be related to an old bug.)

**Comment by elemoine** [comment]
The above patch assumes that the coordinates received in the GeoJSON document from the search webservice are longitudes/latitudes. Can you please confirm that this is the case?

**Comment by rmichaelis** [comment]
With the patch it works as expected.
Thanks.

**Comment by elemoine** [comment]
I'll add a commit and merge. Thanks!

**Comment by elemoine** [comment]
New commit added. I'll merge when the build passes on Travis.

**Pull request merged**
