### PR TITLE
Fix scalebar length

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by sbrunner** [comment]
Ready :-)

**Comment by jaykayone** [comment]
I am testing it currently, give me 5 :)

**Comment by jaykayone** [comment]
works great, please merge, thanks!

**Comment by rmichaelis** [comment]
Why is the shortner url only working with POST and no more with GET ? Is there a reason ?

**Comment by sbrunner** [comment]
Yes, the shortener will modify the database than It's recommend to do a `POST`, but it's true that not relay good to get the URL from the query string it will be cleaner id we get it from e JSON :-)

**Pull request merged**
