### PR TITLE
Merge layertree.html and layertreenode.html

### PR DESCRIPTION
**Pull request by elemoine**
This commit merges the layertree.html and layertreenode.html partials into one partial, layertree.html. This is to accomodate https://github.com/camptocamp/ngeo/pull/292.

This is WIP at the moment, as https://github.com/camptocamp/ngeo/pull/292 needs to be reviewed and merged first.

### CODE REVIEW

**Comment by elemoine** [comment]
https://github.com/camptocamp/ngeo/pull/292 is now merged, so this needs to be reviewed and merged as well.

**Comment by petzlux** [comment]
@elemoine tried to build this, did you move the branch from https://github.com/elemoine/ngeo#layertree to https://github.com/elemoine/ngeo/tree/gmf-layertree  ?

**Comment by elemoine** [comment]
Now using `camptocamp/ngeo#master` again. It should work now. It's important to merge this, as the application's catalog should be broken currently.

**Comment by elemoine** [comment]
@petzlux, I still have this one for you :)

**Comment by petzlux** [comment]
LGTM !

**Comment by elemoine** [comment]
Cool. Thanks for testing.

**Pull request merged**
