### PR TITLE
Add theme to permalink

### PR DESCRIPTION
**Pull request by elemoine**

### CODE REVIEW

**Comment by elemoine** [comment]
This PR requires https://github.com/Geoportail-Luxembourg/geoportailv3/pull/403, which should be merged first. But the code is ready for review, the relevant commit being 68e2e3e.

So permalinks of the forms `/theme/{theme}` and `/{theme}` are handled. When a permalink of the form `/{theme}` is received it is immediately changed to `/theme/{theme}`.

The behavior is as discussed in https://github.com/Geoportail-Luxembourg/geoportailv3/issues/400, that is:

* The theme is never stored in the local storage,
* When no theme is specified in the URL the "main" theme is used.

Please review.

There's one important bit that is missing, and that I'd like to discuss and address with a separate PR:

Currently URLs of the form `/{theme}` lead to 404s. This is because c2cgeoportal does not define a route for the `/{theme}` URL pattern. So we somehow need to add a route to handle `/{theme}` URLs. What do you think @sbrunner?

**Comment by sbrunner** [comment]
In c2cgeoportal it's possible to add a route on `<apache_entry_point>/wsgi/<theme>` but for the `<apache_entry_point>/<theme>` we should create a rewrite rule, for that it can be possible but for that `c2c.template` should read the database. Then it's requires more development ...

**Comment by jaykayone** [comment]
in geoportailv2, we had this type of config:

map.connect('/:theme', controller='home', action='index')

isn't this an option?

**Comment by elemoine** [comment]
> In c2cgeoportal it's possible to add a route on <apache_entry_point>/wsgi/<theme> but for the <apache_entry_point>/<theme> we should create a rewrite rule, for that it can be possible but for that c2c.template should read the database. Then it's requires more development ...

The only thing we need is a route for `/<theme>` **in** the WSGI application. The rest will be addressed with rewrite rules on the Luxembourg side (@jaykayone?).

@sbrunner, for the `/<theme>` route, do you think it should be defined in c2cgeoportal or in the application? That sounds like an application-specific route to me. The problem is that the URL pattern is application-specific, but the corresponding view is defined in c2cgeportal.

**Comment by elemoine** [comment]
> in geoportailv2, we had this type of config:
> 
> map.connect('/:theme', controller='home', action='index')
> 
> isn't this an option?

Yes, I am just wondering where the route should be defined.

**Comment by sbrunner** [comment]
@elemoine with `/<theme>` you want to say `/wsgi/<theme>` right ?

**Comment by jaykayone** [comment]
>  Yes, I am just wondering where the route should be defined.

@elemoine in that case it is not an apache/wsgi rewrite rule but a pyramid routing config, or am i missing something?

**Comment by elemoine** [comment]
> @elemoine in that case it is not an apache/wsgi rewrite rule but a pyramid routing config

Yep.

**Comment by elemoine** [comment]
> @elemoine with /<theme> you want to say /wsgi/<theme> right ?

Yes, this is why I said `/{theme}` **in** the WSGI app.

**Comment by elemoine** [comment]
I rebased this. This is ready for review.

**Comment by elemoine** [comment]
Does someone want to review this?

**Comment by rmichaelis** [comment]
I tried to test with my ysgi instance : http://devv3.geoportail.lu/renaud
But I'm directly redirected to http://devv3.geoportail.lu/theme/main?version=3&zoom=10&X=693523&Y=6401189

Should I configure something ?

**Comment by elemoine** [comment]
I hadn't thought about this problem. I'll see what I can do.

**Comment by elemoine** [comment]
I changed the code. I hope it'll also work with modwsgi and `/<instanceid>/wsgi` type roots this time.

**Comment by rmichaelis** [comment]
It works as expected now.

**Comment by elemoine** [comment]
Thanks for testing again. Please tell me if you comments on the code and if/when I can merge this.

**Comment by rmichaelis** [comment]
After reading the current thread, I'm not sure if that url should work or not ? http://devv3.geoportail.lu/renaud/theme/

**Comment by rmichaelis** [comment]
Is the behavior with a a non existing theme correct or not ?
Should the user received a message or something telling him that the theme doesn't exist ?
http://devv3.geoportail.lu/renaud/theme/no_more_existing

**Comment by elemoine** [comment]
> Is the behavior with a a non existing theme correct or not ?
> Should the user received a message or something telling him that the theme doesn't exist ?
> http://devv3.geoportail.lu/renaud/theme/no_more_existing

I assumed that this should never occur, but we can probably handle that if necessary.

**Comment by rmichaelis** [comment]
Some themes are protected and need to be authenticated before being accessed.
We should be redirected to the login page.

**Comment by elemoine** [comment]
> Some themes are protected and need to be authenticated before being accessed.
> We should be redirected to the login page.

I don't think that's related to that PR, no?

**Comment by jaykayone** [comment]
ad: themes that do not exist: this is an error that should be caught

ad: authtification, this can be done in another PR but it is closely related

**Comment by elemoine** [comment]
This PR is about reading/writing the "theme" part of permalinks. It's not related to authentication and redirecting the user to a login page. I'd suggest that we create a new issue and discuss redirection there.

But I agree we could better handle unknown themes. Should we just use the main theme when the one specified in the URL is unknown or should we also display an error message to the user? As I understand it permalinks are not something users manually create, so my feeling is that we can just use the "main" theme if the one specified in the URL is unknown, with no error message.

**Comment by jaykayone** [comment]
yes this is ok for me too

**Comment by elemoine** [comment]
I've changed the code to use the default theme (`main`) if the theme specified in the URL is not valid.

**Comment by elemoine** [comment]
And I created https://github.com/Geoportail-Luxembourg/geoportailv3/issues/446 for the "protected themes" issue.

**Pull request merged**
