### PR TITLE
tracing

### PR DESCRIPTION
**Pull request by jaykayone**
@rmichaelis can you review this please when you are back ?

### CODE REVIEW

**Comment by rmichaelis** [comment]
@jaykayone I've just deployed on staging env. Could you please have a try and tell me if it's ok with colors and presentation?

**Comment by jaykayone** [comment]
i'd prefer that the yellow one would still be visible on top

**Comment by rmichaelis** [comment]
better now ?

**Comment by jaykayone** [comment]
yes

**Comment by rmichaelis** [comment]
Should we merge and close this one ?

**Comment by jaykayone** [comment]
yes

**Pull request merged**
