### PR TITLE
Show an example of actions items in dropdown menu

### PR DESCRIPTION
**Pull request by pgiraud**
With some more general styling.

Please review.

### CODE REVIEW

**Comment by jaykayone** [comment]
@rmichaelis 
can you put this on your demo server please?

**Comment by rmichaelis** [comment]
done : http://devv3rm.geoportail.lu/short/f6Ij

**Comment by rmichaelis** [comment]
done : http://devv3.geoportail.lu/renaud

**Comment by jaykayone** [comment]
LGTM (result, not talking about the code which I have not checked)

**Comment by rmichaelis** [comment]
Looks good to me. Are you ready to merge ?

**Pull request merged**
