### PR TITLE
Piwik tracking improvements

### LINKED ISSUE #1490: language tracking
track language settings in piwik

### PR DESCRIPTION
**Pull request by petzlux**
fix #1490

### CODE REVIEW

**Comment by petzlux** [comment]
@rmichaelis LGTM ?

**Comment by petzlux** [comment]
bug when changing theme, pushes last layer as event again ...

**Comment by petzlux** [comment]
@rmichaelis can we merge now, the issue with the logging of layers you showed this morning is solved.

**Comment by rmichaelis** [comment]
Should the external WMS layers be logged as a specific layer ? Otherwise it looks good to me.

**Pull request merged**
