### PR TITLE
Fix longpress

### LINKED ISSUE #1779: long press on mobile
android

### PR DESCRIPTION
**Pull request by rmichaelis**
Fixes #1779 
@petzlux @jaykayone @adonno Could you please test longpress as well as layer querry on different devices and browsers?
http://devv3.geoportail.lu/renaud
Thanks

### CODE REVIEW

**Comment by jaykayone** [comment]
now broken on ios ;(

**Comment by rmichaelis** [comment]
Is only the longpress broken ? Is query working ?

**Comment by jaykayone** [comment]
yes

**Comment by rmichaelis** [comment]
Should be fixes. Please try again.

**Comment by petzlux** [comment]
Android Chrome.

Double click to zoom doesnt function reliably, ie if for example parcels are displayed, they are selected as well .. this happens every time. on prod it happens only sometimes...

**Comment by rmichaelis** [comment]
Should be ok now. Could you please clean the browser cache and try again ?

btw double click zoom does not work on my android chrome.

**Pull request merged**
