### PR TITLE
fix #517

### LINKED ISSUE #517: sqlalchemy.exc.ArgumentError at application init time
Since https://github.com/Geoportail-Luxembourg/geoportailv3/pull/452 was merged I get an error at application init time:

```
-------------------- Restarting --------------------
Traceback (most recent call last):
  File ".build/venv/bin/pserve", line 9, in <module>
    load_entry_point('pyramid==1.6.dev0', 'console_scripts', 'pserve')()
  File "/home/elemoine/src/geoportailv3/.build/venv/src/pyramid/pyramid/scripts/pserve.py", line 58, in main
    return command.run()
  File "/home/elemoine/src/geoportailv3/.build/venv/src/pyramid/pyramid/scripts/pserve.py", line 328, in run
    global_conf=vars)
  File "/home/elemoine/src/geoportailv3/.build/venv/src/pyramid/pyramid/scripts/pserve.py", line 363, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 203, in invoke
    app = context.app_context.create()
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/elemoine/src/geoportailv3/geoportailv3/__init__.py", line 68, in main
    sqlalchemy.create_engine(engines[engine]), name=engine)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 362, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 49, in create
    u = url.make_url(name_or_url)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 176, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/elemoine/src/geoportailv3/.build/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 225, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name)
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'Allow from 127.0.0.1 ::1'
```

This is related to `sqlalchemy_engines` [variable](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/7f6aabbcbeffe1f8a7371003f0fbad85d37522ed/geoportailv3.mk#L19) that was added by #452.

Does anyone know what's going on?

### PR DESCRIPTION
**Pull request by rmichaelis**
Fixes https://github.com/Geoportail-Luxembourg/geoportailv3/issues/517.

### CODE REVIEW

**Comment by elemoine** [comment]
Yep, it works. Please merge.

But I think there's a bug in c2c.template or something, which #452 revealed, and which this commit hides. It is indeed not normal to see an error like `sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string 'Allow from 127.0.0.1 ::1'` when a variable is not defined.

**Comment by elemoine** [comment]
Thank you Renaud!

**Comment by sbrunner** [comment]
@elemoine witch kind if issue do you think there is in c2c.template ?

**Comment by elemoine** [comment]
Have you seen the initial issue that I created? #517

**Comment by sbrunner** [comment]
Too quickly :-), I report it to c2c.template

**Pull request merged**
