### PR TITLE
mymaps icons

### PR DESCRIPTION
**Pull request by pgiraud**
As a follow up to #928.
This adds icons in the features lists.

### CODE REVIEW

**Comment by jaykayone** [comment]
@pgiraud: what is the state of this PR?

**Comment by petzlux** [comment]
will review and merge if okay

**Comment by petzlux** [comment]
Unfortunately, the Pull request is not functionally complete. all objects get a polygon icon. 

@pgiraud as I have no idea how to create or include more icons, could you do this for the following types today? I would then finish the code to show the relevant icons for Point, Label, Line, Polygon and Circle.

**Comment by pgiraud** [comment]
The instructions on how to modify the web font used for icons is described in the following WIKI page.
https://github.com/Geoportail-Luxembourg/geoportailv3/wiki/Fonts

**Comment by pgiraud** [comment]
I agree that the pull request is not ready to be merged. Though the icons are ready to be used (at least for point, lines, and polygons), the "polygon" icon is used whatever the type of geometry is.

**Comment by petzlux** [comment]
@pgiraud thanks for the instructions, will take it from there!

**Comment by petzlux** [comment]
okay we now have separate icons for point & label, line, and polygon & circle. 

@rmichaelis can you review

**Comment by rmichaelis** [comment]
Looks good to me. Please merge.

**Pull request merged**
