### PR TITLE
Handle shortlinks in print

### LINKED ISSUE #470: Handle shortlinks in print
The shortlink we send to MapFish Print is currently hard-coded. Instead we should send a shortlink that matches the current state of the application.

Related to https://github.com/Geoportail-Luxembourg/geoportailv3/pull/445.

### PR DESCRIPTION
**Pull request by elemoine**
This PR factors out the "interact with shorturl web service" code in a specific Angular service, and make the shorturl and the print directives rely on that service.

Unfortunately the "shorturl" web service does not work locally on my dev environment. It returns short URLs that look like this: `http://localhost/elemoine/s/PIR4` (the port number has been removed, and the instanceid has been added).

@petzlux, could you please review this? In the mean time, I can try to test it on our dev server.

Fixes #470.

### CODE REVIEW

**Comment by petzlux** [comment]
Will do

Concerning the URLs, it seems that c2cgeoportal doesnt support [Port number in the template](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/vars_wepa.yaml#L10), I don't know about the instance name, which didnt get attached in my setup ... I believe this is an upstream issue in c2cgeoportal

**Comment by elemoine** [comment]
> Concerning the URLs, it seems that c2cgeoportal doesnt support Port number in the template, I don't know about the instance name, which didnt get attached in my setup ... I believe this is an upstream issue in c2cgeoportal

Definitely, and one that may not be easy to fix. We will have to talk to @sbrunner about that.

**Comment by petzlux** [comment]
In practice, for our deployment might not matter much, as we will use http://g-o.lu domain , with no port number ...

**Comment by petzlux** [comment]
Shorturl refactor is okay, regarding print functionality, I dont have a working print setup , so cant review this bit. @jaykayone can you help me there ?

**Comment by jaykayone** [comment]
no working setup here either ..

**Comment by jaykayone** [comment]
On http://devv3.geoportail.lu/main there is a print service running (tomcat), but the printproxy does not seem to work:

http://devv3.geoportail.lu/main/wsgi/printproxy/status/undefined.json 

The page keeps sending bad requests once the print button has been pushed
screen shot 2015-05-21 at 08 55 16

**Comment by elemoine** [comment]
@jaykayone I think it'd be good to discuss that issue elsewhere as it is unrelated to the shorcurl support. I'll create a separate issue.

**Comment by jaykayone** [comment]
ok

**Comment by petzlux** [comment]
For me looks okay to merge ! @elemoine

**Comment by petzlux** [comment]
Can this be merged and the print problem be adressed in a separate pull request ?

**Comment by petzlux** [comment]
Just wanted to ask again if this can be merged, as I would like to use the shorturl service for #205

**Comment by elemoine** [comment]
I have a problem with merging this because, because of the shortlink issue, printing would not work on people's development environments. So I'd like to find a solution first. @sbrunner suggested a solution to me, but I still need to test it.

Can't you just extract out the shorturl service from my branch into yours? I can rebase my branch onto master if your branch is merged into master before mine.

**Comment by petzlux** [comment]
Okay will try !

**Comment by elemoine** [comment]
I've made progress with this, but I have one remaining problem: geoportailv3's `qr` service won't create a QR code image for me because the input URL (which looks like this `http://localhost:5000/short/q9R1`) does not pass the [regex](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/master/geoportailv3/views/qr.py#L16-L17). @jaykayone, do you think we can relax the regex a bit?

**Comment by jaykayone** [comment]
@petzlux already did that in his right click PR

**Comment by elemoine** [comment]
> @petzlux already did that in his right click PR

Nice!

**Comment by elemoine** [comment]
I've cherry-picked @petzlux's change to `qr.py`: https://github.com/Geoportail-Luxembourg/geoportailv3/commit/df4e4af7a014e8bdf55c072aa4bc08ea849fd7fe.

This is ready to be merged from my point of view. @petzlux will need to rebase his branch onto master if we merge my branch before his.

**Comment by elemoine** [comment]
I am happy to merge this if @petzlux agrees to rebase his branch onto master when this is merged :-)

**Comment by petzlux** [comment]
:+1:  yes will rebase

**Pull request merged**
