### PR TITLE
More flashy color proposal

### LINKED ISSUE #1354: change color of notifications to be more visible

### PR DESCRIPTION
**Pull request by rmichaelis**
Fixes #1354

### CODE REVIEW

**Comment by rmichaelis** [comment]
image

@jaykayone what about this one?

**Comment by jaykayone** [comment]
i think the contrast difference is too low. what abt black fonts. @petzlux? 

otherwise red on grey?

check with accessibility criteria for contrast please

**Comment by petzlux** [comment]
After discussion with @rmichaelis 

Introduce a classification system for notifications. ie have more important ones (like when layers conflicts arise, server reply empty ...) and less critical notifications (drawing tooltips)

Then we can style differentially, and make critical alerts stand out even more ...

**Comment by pgiraud** [comment]
Red color for text should be restricted to critical alert messages.

**Comment by rmichaelis** [comment]
Messages are now classified. (Info, Warning, Error) Please take a look here and help me to choose the right color for each classification: http://devv3.geoportail.lu/renaud

**Pull request merged**
