### PR TITLE
Languages4

### PR DESCRIPTION
**Pull request by petzlux**

### CODE REVIEW

**Comment by elemoine** [comment]
This PR included a commit from Stéphane (https://github.com/Geoportail-Luxembourg/geoportailv3/commit/42ab89786a31a5fa40a3d890c789dd858cbd061d). Was it wanted?

It also includes a merge commit (https://github.com/Geoportail-Luxembourg/geoportailv3/commit/de9b9eb5175631a90920d416b5a372a8e475554c), which should not have been needed with a proper rebase.

**Comment by petzlux** [comment]
Okay if I understand correctly Stephanes commit reverts his earlier commit? 

Regarding the merge I just followed githubs instructions,  still confused when to use merge vs rebase …

**Comment by elemoine** [comment]
Yes it looks like it reverts one of its earlier commit. But that's not the point. It strikes me as odd that your PR includes a commit from Stéphane. Did Stéphane push that revert commit to one of your languages branches? I doubt it.

I know you used GitHub's merge button. That indeed created a new merge commit, corresponding to the "from languages4 to master" merge. But before that, your languages4

**Comment by jaykayone** [comment]
I guess that stephane 's revert commit is one of those that had been lost yesterday just like pierre's and renaud's but we did not notice. as it was now remerged it has reappeared, just as would have pierre's and renaud's if we had not repaired it before

**Comment by sbrunner** [comment]
It's strange, I don't have this commit in my history, and we don't want this commit ...
I will create a new pull request to correct that :-)

**Comment by petzlux** [comment]
Okay thanks !

**Comment by elemoine** [comment]
@petzlux feel free to delete the languages4  branch.

**Pull request merged**
