### PR TITLE
Add "export features" functionality (WIP)

### PR DESCRIPTION
**Pull request by elemoine**
This PR is WIP for adding "export features" functionality. This is not ready for review.

Depends on https://github.com/camptocamp/c2cgeoportal/pull/1758.

Note: this is how I triggert a feature export from the console:
```js
angular.element(document.body).injector().get('appDrawnFeatures').exportFeaturesAsGpx()
```

### CODE REVIEW

**Comment by elemoine** [comment]
https://github.com/camptocamp/c2cgeoportal/pull/1758 is merged, but we will need to use the next 1.6 release of c2cgeoportal.

**Comment by jaykayone** [comment]
Ok, can you do the upgrade please?

**Comment by elemoine** [comment]
> Ok, can you do the upgrade please?

The problem is that there's no appropriate 1.6 release at this point.

**Comment by jaykayone** [comment]
I see :)

**Comment by elemoine** [comment]
The code in this PR is based on c2cgeoportal's `exportgpxkml` service. This service was added to the 1.6 branch of c2cgeoportal, but there's currently no c2cgeoportal release that includes that service. So two options: either wait for the next 1.6 release or get c2cgeoportal 1.6 from GitHub.

**Comment by jaykayone** [comment]
when is the release planned @sbrunner?

On Thu, Nov 12, 2015 at 9:01 AM, Éric Lemoine <notifications@github.com>
wrote:

> The code in this PR is based on c2cgeoportal's exportgpxkml service. This
> service was added to the 1.6 branch of c2cgeoportal, but there's currently
> no c2cgeoportal release that includes that service. So two options: either
> wait for the next 1.6 release or get c2cgeoportal 1.6 from GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Geoportail-Luxembourg/geoportailv3/pull/932#issuecomment-156028944>
> .
>



-- 
Jeff Konnen

**Pull request closed without merging**
