### PR TITLE
Legend specs needs to be an empty array instead of null

### PR DESCRIPTION
**Pull request by pgiraud**

### CODE REVIEW

**Comment by elemoine** [comment]
Please merge.

**Comment by sbrunner** [comment]
No it should be null or better undefined ...

**Comment by sbrunner** [comment]
We don't want to build the PDF merger for nothing
https://github.com/Geoportail-Luxembourg/geoportailv3/blob/print-store-db/geoportailv3/views/luxprintproxy.py#L125

**Comment by sbrunner** [comment]
See also:
https://github.com/Geoportail-Luxembourg/geoportailv3/commit/319c1954c58b32bc741b46c52726907241035fba

**Comment by elemoine** [comment]
@sbrunner, please provide a PR.

**Comment by sbrunner** [comment]
Already done here: https://github.com/Geoportail-Luxembourg/geoportailv3/pull/640/commits :-)

**Comment by sbrunner** [comment]
Second commit :-)

**Comment by elemoine** [comment]
Ok, so let's close this without merging.

**Pull request closed without merging**
