### PR TITLE
Less travis faild by trying two times the download tasks

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by rmichaelis** [comment]
good idea :-)

**Comment by elemoine** [comment]
The build failed :(

**Comment by sbrunner** [comment]
Because of that:  #653 then I will rebase :-)

**Comment by sbrunner** [comment]
Tests will pass ... :-)

**Comment by jaykayone** [comment]
they did, please merge

**Comment by petzlux** [comment]
can we merge this so that hopefully travis will function better ?

**Comment by elemoine** [comment]
I think we can merge this, but I am afraid this would hide a problem with pypi.camptocamp.net.

I just tried to update my instance and it failed because of errors when downloading packages from pypi.camptocamp.net.

@sbrunner, have you also experienced problems again with our pypi service?

**Comment by jaykayone** [comment]
let's merge this anyway

**Pull request merged**
