### PR TITLE
3d in Catalog/layertree

### PR DESCRIPTION
**Pull request by RemiDesgrange**
Please, @tonio @llienher @mki-c2c test the performance since it seems way better to me (but only tested on my laptop).

It lacks history though.

### CODE REVIEW

**Comment by RemiDesgrange** [comment]
It needs squash :-)

**Comment by jaykayone** [comment]
We've got a demo tomorrow to show the mesh and as I read this, this PR should do some magic to improve speed.
Do you think you can merge it today?

**Comment by tonio** [comment]
I just start test/review right now.

**Comment by jaykayone** [comment]
great, thanks

**Review by tonio — APPROVED** [review]

**Pull request merged**
