### PR TITLE
sort MyMaps Maps by date

### LINKED ISSUE #972: Need to be able to sort MyMaps in chronological order
This necessitates a server side timestamp of last accessed, changed, created ...

### PR DESCRIPTION
**Pull request by petzlux**
fix #972

### CODE REVIEW

**Comment by petzlux** [comment]
The date time strings at the moment are not translated to the correct locale. This is a fundamental problem as the angular `$locale` service is not setup in our project. There will be some work to get this going and have nicely formatted datetime strings in our 4 languages ... 

https://docs.angularjs.org/guide/i18n

**Comment by petzlux** [comment]
and of course, angular locale is one of the services not included in the google closure externs  ... 

https://github.com/google/closure-compiler/blob/8a24212aed468840953fa651ab07130d9bd51c54/contrib/externs/angular-1.4.js#L25

**Comment by petzlux** [comment]
Okay, compromise that we only show short date 23/12/2015

**Comment by petzlux** [comment]
@rmichaelis please review

**Comment by rmichaelis** [comment]
Looks good to me. 
Not directly related to this one, but the cursor icon should probably be a hand to show that the line is selectable.

**Comment by petzlux** [comment]
done cursor changes now 
will merge once travis is happy

**Pull request merged**
