### PR TITLE
Migration of typeahead to 0.11.1 after ngeo update

### LINKED ISSUE #988: add layer trough search box
I cannot add a layer anymore by selecting in the search box

### PR DESCRIPTION
**Pull request by petzlux**
fix #988

### CODE REVIEW

**Comment by petzlux** [comment]
@rmichaelis ready for review

**Comment by rmichaelis** [comment]
Please rebase to avoid Travais failure.

**Comment by rmichaelis** [comment]
The hover is not working anymore.

**Comment by rmichaelis** [comment]
In some cases after selecting a result, the cross button to delete the search words disappears.

**Comment by rmichaelis** [comment]
Probably not related, but after selecting a result the search box should be empty to be able to start a new search.

**Comment by rmichaelis** [comment]
The i button should be on the same line as the text.

image

**Comment by petzlux** [comment]
Okay I see that the translation do not get loaded on language change. will investigate .

**Comment by petzlux** [comment]
the search result should stay in the search box so that the user can see what he selected from the search. on a new click into the search box, then the text should be all selected so that he can start typing again ...

**Comment by petzlux** [comment]
@rmichaelis can you review now again please

**Comment by petzlux** [comment]
@rmichaelis  in what browser did you see the search results not aligned with the information icon ?

**Comment by rmichaelis** [comment]
In firefox

**Comment by rmichaelis** [comment]
The problem with the misalign I button, only occurs in FF

**Comment by rmichaelis** [comment]
The title is not always corresponding with the kind of result.
Example : Orthopédie is not an adress.
image

**Comment by rmichaelis** [comment]
In IE, 2 crosses in the search box.

image

**Comment by petzlux** [comment]
At the moment both POI-s and Adresses are merged under the Adresses. I dont think the user makes the distinction like we do ... 

Concerning IE, i think it uses its own internal text box clearing css ....

**Comment by rmichaelis** [comment]
In the previous version, category and corrsponding text were highlighted on mouse hover.

**Pull request merged**
