### PR TITLE
Share a mymaps

### LINKED ISSUE #787: Permalien d'accès direct à la carte
Link to #782

### PR DESCRIPTION
**Pull request by rmichaelis**
Fixes #787

### CODE REVIEW

**Comment by rmichaelis** [comment]
@petzlux 
As disussed, sharing a mymaps is now in the sharing tools, and no more in mymaps. 
Could you please review ?

**Comment by petzlux** [comment]
@rmichaelis Not sure if this is connected to this pull request, but if the mymap loaded does not have a bgLayer set, than no background map gets loaded

````
{layers_visibility: "true,true,true", rating: 4, create_date: "2013-03-19 09:05:35", bg_layer: "",…}
bg_layer: ""
bg_opacity: 34
category_id: 999
create_date: "2013-03-19 09:05:35"
description: "Wann se moies fësche ginn juppeidi juppeida"
label: ""
layers: "arrets_bus,,"
layers_indices: "5,8,9"
layers_opacity: "1,1,1"
layers_visibility: "true,true,true"
public: false
rating: 4
rating_count: 1
selected_node: "None"
theme: "main"
title: "Dem Fränz säin Treppeltour zu Useldéng"
update_date: "2015-10-22 16:08:53"
user_login: "fk"
uuid: "5bdb79809cba46a98ebab6f1b13c9116"
x: 92959.3
y: 66933.6
zoom: 9
````

**Comment by rmichaelis** [comment]
For my point of view, if no bg_layer is set, then no background layer is displayed ?
What do you expect  as behaviour?

**Comment by petzlux** [comment]
Even the  ````blank```` bgLayer is saved as ````bgLayer:blank````  , not an empty string ... So this seems to me like a case from old mymaps that we either need to convert on the server side, or take into account when loading a mymap

**Comment by petzlux** [comment]
please also see #971

**Comment by petzlux** [comment]
LGTM other issue will be addressed separately

**Pull request closed without merging**
