### PR TITLE
Measure tools

### PR DESCRIPTION
**Pull request by pgiraud**
Adds tools to measure length, area, and azimut.

### CODE REVIEW

**Comment by pgiraud** [comment]
Hi all, now that the measure interactions have been added to ngeo, the current pull request is ready for review.
Can someone on Luxembourg's side give it a try? Don't forget to update the node modules.

**Comment by jaykayone** [comment]
OK I'll give it a try

**Comment by jaykayone** [comment]
This is truly great work.

Things I miss:
- icons
- surface fill color
- for length and surface the moment where you go from m to km resp m2 to km2 is too early. For length, I would only switch to km at 1000m (and not 10m), for surfaces, I would also use ar and hectar
- Azimut: Distance and elevation offset in the label

But I guess all these points can be done by @rmichaelis 

some minor "bugs" we saw:
- when you zoom out while measuring a surface, the label becomes too big and you cannot place a vertex on / under the label
- the azimut tool blocks panning. you cannot pan unless you deactivate the tool
- when clicking X to close the measure panel, tools are not deactivated

**Comment by pgiraud** [comment]
> icons

Can be done on your side.

> surface fill color

Can be configured in the application.

> for length and surface the moment where you go from m to km resp m2 to km2 is too early. For length, I would only switch to km at 1000m (and not 10m), for surfaces, I would also use ar and hectar

I think we need a better algorithm with number of digits precision.
For surfaces in ares and hectares, I propose we address this later.

> Azimut: Distance and elevation offset in the label

Distance in the tooltip can be easily added.
Elevation offset will be a bit trickier. Can you please open an issue for this?

> when you zoom out while measuring a surface, the label becomes too big and you cannot place a vertex on / under the label

Do someone really want to draw a polygon in such a context?

> the azimut tool blocks panning. you cannot pan unless you deactivate the tool

See https://github.com/camptocamp/ngeo/pull/166.

> when clicking X to close the measure panel, tools are not deactivated

This should be addressed in the application in my opinion.

**Comment by jaykayone** [comment]
OK, we'll wait for you to merge this PR so @rmichaelis can take over

**Comment by pgiraud** [comment]
up

**Comment by elemoine** [comment]
Looking at it now…

**Comment by elemoine** [comment]
I suggest to not use `ng-controller` and use a measure directive instead. See https://github.com/Geoportail-Luxembourg/geoportailv3/compare/elemoine_measure.

**Comment by jaykayone** [comment]
I have just seen a big problem.
The measures are taken in EPSG:3857, whereas we need to have them in EPSG:2169.

This makes a huge difference. A distance measured as 200m in webmercator makes 130m in LUREF!

**Comment by elemoine** [comment]
http://blogs.esri.com/esri/arcgis/2010/03/05/measuring-distances-and-areas-when-your-map-uses-the-mercator-projection/ is interesting.

**Comment by jaykayone** [comment]
I see that your googling skills are the same than ours :-)

**Comment by elemoine** [comment]
@jaykayone @pgiraud and I discussed it and we think there are solutions. So I'd suggest that we merge this and address the remaining issues with separate PRs.

**Comment by jaykayone** [comment]
ok, can you open a separate issue for this please?

**Comment by elemoine** [comment]
@pgiraud, please rebase and merge. I'm going to create an issue for the projection issue.

**Pull request merged**
