### PR TITLE
Change map zoom when changing print scale

### PR DESCRIPTION
**Pull request by elemoine**
This PR aims to address #759. This is WIP for the moment.

### CODE REVIEW

**Comment by elemoine** [comment]
This is ready for testing.

So when changing to a smaller a print scale the map is zoomed out if the print rectangle no longer fits into the map viewport.

Please test.

**Comment by petzlux** [comment]
Functionally looks good to me !

**Comment by jaykayone** [comment]
+1

**Comment by elemoine** [comment]
Ok, I'll add units tests to https://github.com/camptocamp/ngeo/pull/367 and update this branch when the ngeo PR is merged.

**Pull request merged**
