### PR TITLE
Select mymaps or query layer depending on the tab where the user is

### PR DESCRIPTION
**Pull request by rmichaelis**

### CODE REVIEW

**Comment by rmichaelis** [comment]
@jaykayone Please test on "/renaud"

**Comment by geoportallux** [comment]
Hmmm … here it is not working like I expect:

http://devv3.geoportail.lu/renaud/theme/tourisme?version=3&zoom=12&X=677374&Y=6386065&lang=en&layers=512-386&opacities=1-1&bgLayer=topo_bw_jpeg&map_id=a06de7e724e9459db930d65487ecb6d6&crosshair=false

**Comment by rmichaelis** [comment]
Ok, we will have a look together tomorrow.

**Comment by rmichaelis** [comment]
@jaykayone Could you please check again ?

**Comment by jaykayone** [comment]
great

**Pull request merged**
