### PR TITLE
add basic piwik tracking

### PR DESCRIPTION
**Pull request by petzlux**

### CODE REVIEW

**Comment by petzlux** [comment]
@jaykayone LGTM ?

**Comment by rmichaelis** [comment]
This http://apps.geoportail.lu/exemple_api/apiv3_demo.html is based on your branch, but I don't find the call to piwik in my network panel.

**Comment by petzlux** [comment]
Did you do a fresh build ?

**Comment by rmichaelis** [comment]
Yes I did. 
I see that piwik.js is loaded, but I don't see the call to piwik.php

**Comment by rmichaelis** [comment]
LGTM

**Pull request merged**
