### PR TITLE
clickable title and delete button

### PR DESCRIPTION
**Pull request by rmichaelis**
could you please check on mobile devices ?

### CODE REVIEW

**Comment by rmichaelis** [comment]
could be tested here : devv3.geoportail.lu/renaud

**Comment by petzlux** [comment]
screenshot_2015-07-16-11-33-20

**Comment by petzlux** [comment]
:-1:

**Comment by rmichaelis** [comment]
Does it work with a layer having a shorter name ?

**Comment by petzlux** [comment]
Nope

screenshot_2015-07-16-11-56-05

**Comment by rmichaelis** [comment]
what browser are you using ?

**Comment by petzlux** [comment]
chrome on android 5

**Comment by jaykayone** [comment]
on iOS it works great

**Comment by rmichaelis** [comment]
@petzlux is it better now ? It works fine on my android devices.

**Comment by petzlux** [comment]
Yes works now!

**Comment by rmichaelis** [comment]
As discussed I've just added the ellipsis right to the title.
Is this now ready to merge ?

**Comment by petzlux** [comment]
I am of the opinion that we should hide the ellipsis on desktop , as this is just a hint for mobile / tablet users, that they can expand the layer tile ... this would simply be a css rule

**Comment by jaykayone** [comment]
the dots are now too close to the bin and the text is not shown entirely



we should rediscuss this tomorrow

**Comment by rmichaelis** [comment]
Do you have a screenshot ?

**Comment by jaykayone** [comment]
now it is OK.
as far as I know, we currently do not have another option to detect mobile as the size, which does not really detect tablets correctly. 
In that regard I suggest that we should show the ellipses everywhere until we have a possbility to sniff the touch capability of a device

**Pull request merged**
