### PR TITLE
Improve mymaps experience

### PR DESCRIPTION
**Pull request by rmichaelis**

### CODE REVIEW

**Comment by rmichaelis** [comment]
Fixes #1246 #1297 #1296 #1289

**Comment by rmichaelis** [comment]
@jaykayone Thanks to test this PR here : http://devv3.geoportail.lu/renaud/

**Comment by jaykayone** [comment]
will do Sir
You can expect clearance before Monday

**Comment by jaykayone** [comment]
looks very good.
some minor comments:
- imported lines should not be dashed by default
- click tolerance still too low (hard to click on line sometimes and too easy to stop editing when trying to delete a vertex)
- double click to finish popup is annoying now that we took away everthing else. it could go into the left panel too

**Comment by jaykayone** [comment]
but the tool is now about 10x better to use

**Comment by rmichaelis** [comment]
- Click tolerance is now higher. Is it better now ?
-  "imported lines should not be dashed by default" is part of a new PR.
-  "double click to finish popup", Not sure to understand what you wish.

**Comment by jaykayone** [comment]
tolerance is perfect now

**Comment by jaykayone** [comment]
* "double click to finish popup", Not sure to understand what you wish.
Actually I do not want the "click to draw, double click to terminate" popup to be shown on the map when popup is minimized but in the left bar somewhere, just as all the other stuff

**Comment by rmichaelis** [comment]
Thanks for the clarification. I understand now.  But not sûre where to put it. I'll make à proposal monday

**Comment by jaykayone** [comment]
if you want to merge, you can put that into another PR

**Comment by rmichaelis** [comment]
I can Merge but not deploy. I'm notre near a computer right now.

**Pull request merged**
