### PR TITLE
Get image type from layer spec

### LINKED ISSUE #355: Take image_type into account
As [commented](https://github.com/Geoportail-Luxembourg/geoportailv3/issues/300#issuecomment-83639253) in #300 the js code that creates OpenLayers layers from layer nodes should take the `image_type` property into account.

Restant c2c 01/04/2015 0.25j

### PR DESCRIPTION
**Pull request by elemoine**
Fixes #355.

To be tested. But testing this requires a `themes` response with the `imageType` information.

### CODE REVIEW

**Comment by elemoine** [comment]
This requires updating geoportailv3 with a new version of c2cgeoportal.

**Comment by elemoine** [comment]
This is now ready for review.

**Comment by rmichaelis** [comment]
I tried to install this branch, but I've got a timeout error during the build.
Is this the same kind of issue we already had in the past with the proxy? 

>Obtaining pyramid from git+https://github.com/Pylons/pyramid@1e02bbfc0df09259bf207112acf019c8dba44a90#egg=pyramid (from -r CONST_requirements.txt (line 6))
>  Updating ./.build/venv/src/pyramid clone (to 1e02bbfc0df09259bf207112acf019c8dba44a90)
>  Could not find a tag or branch '1e02bbfc0df09259bf207112acf019c8dba44a90', assuming commit.
>fatal: unable to connect to github.com:
>github.com[0: 192.30.252.129]: errno=Connection timed out

>Clone of 'git://github.com/Pylons/pylons_sphinx_theme.git' into submodule path 'docs/_themes' failed
>  Complete output from command git submodule update --init --recursive -q:

>  ----------------------------------------
>  Command "git submodule update --init --recursive -q" failed with error code 1 in /var/www/vhosts/geoportailv3_mire/.build/venv/src/pyramid
>make: *** [.build/requirements.timestamp] Error 1

**Comment by elemoine** [comment]
> Is this the same kind of issue we already had in the past with the proxy?

Yes, it looks like so. Probably something that we did not actually fix.

**Comment by rmichaelis** [comment]
How to bypass this problem to be able to test the PR ?

**Comment by elemoine** [comment]
The `orthogr_2013_global` background layer now works with this PR. It would also be a good thing to test a few WMS overlays that use jpeg.

**Comment by elemoine** [comment]
@jaykayone I just rebased my branch. It should build now.

**Comment by jaykayone** [comment]
I was finally able to test this, everything works as expected thanks

**Comment by elemoine** [comment]
I realized that I merged this before the code was reviewed. I'm still interested in code reviews. And I'm happy to make changes if there are comments.

**Pull request merged**
