### PR TITLE
Popup is now draggable

### LINKED ISSUE #886: Prettify Info Popup
it should be in the top right corner of the window
Info window: "x" icon too low
move popup for editing vertices

### PR DESCRIPTION
**Pull request by rmichaelis**
fixes #886

### CODE REVIEW

**Comment by rmichaelis** [comment]
Could you please review

**Comment by petzlux** [comment]
After dragging a feature popup, it becomes very hard to close it, have to click multiple times close icon .

**Comment by jaykayone** [comment]
can you put it on /renaud so that I can test too please?

**Comment by petzlux** [comment]
Question for @pgiraud 
This is probably out of scope of this pull request, but what is the logic for having a Popup Directive in geoportailv3 ? I ask, because I can see that ngeo has a Popup Directive https://github.com/camptocamp/ngeo/blob/master/src/services/popup.js

Are there features missing in the ngeo directive that make it necessary to recreate a Popup here?

**Comment by rmichaelis** [comment]
@jaykayone done
@petzlux you are right the closing button should not be used to drag the popup.

**Comment by jaykayone** [comment]
same remark for close button but for the rest it is OK

**Comment by rmichaelis** [comment]
Is it better now ?

**Pull request merged**
