### PR TITLE
Use current theme's print scales

### PR DESCRIPTION
**Pull request by elemoine**
With this PR the print directive uses the current's print scales (`print_scales` in the theme's `metadata`) instead of using a fixed set of scales.

@jaykayone, could you please review this?

### CODE REVIEW

**Comment by jaykayone** [comment]
OK works as expected (see other remarks in https://github.com/Geoportail-Luxembourg/geoportailv3/issues/489)

**Comment by elemoine** [comment]
If ok by you, I'll merge this and address the remaining issue with other PRs.

**Comment by jaykayone** [comment]
OK

**Comment by elemoine** [comment]
I've added a commit that adds default map print scales, which are used if the current theme does not have print scales.

**Pull request merged**
