### PR TITLE
Transifex Client and resource fixes - i18n

### PR DESCRIPTION
**Pull request by petzlux**

### CODE REVIEW

**Comment by sbrunner** [comment]
What does it will fix ?

**Comment by sbrunner** [comment]
It just seem to duplicate things ...

**Comment by petzlux** [comment]
@sbrunner okay, I understand now, looking at makefile, geoportailv3-db.pot & -js.pot are merged to  geoportailv3-client.pot !

Shall we add -db.pot and -js.pot to .gitignore, or add both to the project ?

**Comment by sbrunner** [comment]
Good question, 
Traditionally we commit them, but I think that not needed ...
@elemoine what do you think ?

**Comment by petzlux** [comment]
Okay changed branch to reflect comments, waiting on decision if we exclude or include -db.pot & -js.pot

**Comment by elemoine** [comment]
+1 for not committing them into the project. But in that case I think they should be generated in the `.build` directory, instead of in the `$(PACKAGE)/locale` directory.

**Comment by sbrunner** [comment]
I just create a c2cgeoportal issue for that :-) https://github.com/camptocamp/c2cgeoportal/issues/1199

**Pull request merged**
