### PR TITLE
Fix pyramid revision

### LINKED ISSUE #269: Build fails -
After a rebase from master, the build fails with:

````
Requirement already satisfied (use --upgrade to upgrade): WebOb==1.4 in ./.build/venv/lib/python2.7/site-packages (from -r CONST_versions.txt (line 74))
Requirement already satisfied (use --upgrade to upgrade): zope.component==4.2.1 in ./.build/venv/lib/python2.7/site-packages (from -r CONST_versions.txt (line 75))
Requirement already satisfied (use --upgrade to upgrade): zope.deprecation==4.1.2 in ./.build/venv/lib/python2.7/site-packages (from -r CONST_versions.txt (line 76))
Requirement already satisfied (use --upgrade to upgrade): zope.event==4.0.3 in ./.build/venv/lib/python2.7/site-packages (from -r CONST_versions.txt (line 77))
Requirement already satisfied (use --upgrade to upgrade): zope.interface==4.1.2 in ./.build/venv/lib/python2.7/site-packages (from -r CONST_versions.txt (line 78))
Requirement already satisfied (use --upgrade to upgrade): zope.sqlalchemy==0.7.5 in ./.build/venv/lib/python2.7/site-packages (from -r CONST_versions.txt (line 79))
Obtaining pyramid-closure from git+https://github.com/camptocamp/pyramid_closure#egg=pyramid_closure (from -r CONST_requirements.txt (line 5))
  Updating ./.build/venv/src/pyramid-closure clone
Obtaining pyramid from git+https://github.com/Pylons/pyramid@620bdefbff81792fd047f273a234264ce3d0a764#egg=pyramid (from -r CONST_requirements.txt (line 6))
  Updating ./.build/venv/src/pyramid clone (to 620bdefbff81792fd047f273a234264ce3d0a764)
  Could not find a tag or branch '620bdefbff81792fd047f273a234264ce3d0a764', assuming commit.
^@^@fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection timed out

Clone of 'git://github.com/Pylons/pylons_sphinx_theme.git' into submodule path 'docs/_themes' failed
  Complete output from command /bin/git submodule update --init --recursive -q:

  ----------------------------------------
  Command "/bin/git submodule update --init --recursive -q" failed with error code 1 in /home/wepa/geoportailv3/.build/venv/src/pyramid
make: *** [.build/requirements.timestamp] Error 1
````

The submodules fails to update, because it is specified by git protocol, not https protocol . Needs to be fixed 

Restant c2c 01/03/2015 : 1j

### PR DESCRIPTION
**Pull request by sbrunner**
fix #269

### CODE REVIEW

**Comment by elemoine** [comment]
Could you please explain how this fixes #269 before merging? Thanks.

**Comment by sbrunner** [comment]
I don't exactly why but the previous revision don't exists (anymore ?) ..., the new one is this one: 
https://github.com/Pylons/pyramid/commit/1e02bbfc0df09259bf207112acf019c8dba44a90

**Comment by elemoine** [comment]
The build currently works for me, so I think the previous commit does exist. There must be another problem (proxy-related?) for @petzlux, no?

**Comment by jaykayone** [comment]
the git-protocol-instead-of-https is a proxy issue, yes, see logfile in #269

**Comment by sbrunner** [comment]
It's working for pyramid_closure why it will not work for pyramid ?

**Comment by elemoine** [comment]
> It's working for pyramid_closure why it will not work for pyramid ?

Good point. Let's merge this and see whether it fixes @petzlux's issue.

**Pull request merged**
