### PR TITLE
measure while drawing

### LINKED ISSUE #945: mymaps: show measure while drawing

### PR DESCRIPTION
**Pull request by pgiraud**
Fixes #945

 - [x] line,
 - [x] polygon,
 - [x] circle

### CODE REVIEW

**Comment by pgiraud** [comment]
It was a bit easier than I thought. The circle drawing tool (using the azimut measure interaction) is still specific though.

**Comment by pgiraud** [comment]
Looks like it works for circles now. Yeepee!

**Comment by pgiraud** [comment]
Please test and review.

**Comment by petzlux** [comment]
Works fine with me, cant fault anything with the code

**Pull request merged**
