### PR TITLE
Features Search in selected Layers

### PR DESCRIPTION
**Pull request by mki-c2c**
search features in selected layers
operational for 
- ESRI rest layers
- postgis DB layers

pure WMS layer using the ogc proxy cannot be searched.

Configuration menu for search in POI, layers, features, CMS has to be harmonized with PR https://github.com/Geoportail-Luxembourg/geoportailv3/pull/2533

### CODE REVIEW

**Comment by mki-c2c** [comment]
ESRI part has been tested with external test server for cycling roads.
Postgis request part has been designed by analogy with getfeature parts. Generated queries have been analysed, but there is no full scale test. This part has to be tested on nextprod

**Comment by jaykayone** [comment]
> ESRI part has been tested with external test server for cycling roads.
> Postgis request part has been designed by analogy with getfeature parts. Generated queries have been analysed, but there is no full scale test. This part has to be tested on nextprod


> search features in selected layers
> operational for
> 
> * ESRI rest layers
> * postgis DB layers
> 
> pure WMS layer using the ogc proxy cannot be searched.
> 
> Configuration menu for search in POI, layers, features, CMS has to be harmonized with PR #2533


Is there any reason why "standard" WMS can not be searched? This should be possible regarding the settings found in the getfeaturedefinition table, independently if it is an external wms, internal wms, esri wms or wmts.
what counts is the setting of the getfeature table, which source can be used to search on a given field

**Comment by mki-c2c** [comment]
> Is there any reason why "standard" WMS can not be searched? This should be possible regarding the settings found in the getfeaturedefinition table, independently if it is an external wms, internal wms, esri wms or wmts.
> what counts is the setting of the getfeature table, which source can be used to search on a given field

I might be wrong but I am not aware of a capability to search in a pure WMS layer (e.g. running on a MapServer)

The setting in getfeature table defines only the type of data source:

- engine & query defined => postgis query
- rest_url definied => arcgis query
- no engine / query & no rest_url => ogc proxy, pure WMS => no search function

there could be some clarification by using an explicit data type: arcgis vs. postgis vs. mapserver, but I could not figure out how to search in a mapserver WMS service.

**Comment by jaykayone** [comment]
> > Is there any reason why "standard" WMS can not be searched? This should be possible regarding the settings found in the getfeaturedefinition table, independently if it is an external wms, internal wms, esri wms or wmts.
> > what counts is the setting of the getfeature table, which source can be used to search on a given field
> 
> I might be wrong but I am not aware of a capability to search in a pure WMS layer (e.g. running on a MapServer)
> 
> The setting in getfeature table defines only the type of data source:
> 
> * engine & query defined => postgis query
> * rest_url definied => arcgis query
> * no engine / query & no rest_url => ogc proxy, pure WMS => no search function
> 
> I could imagine some clarification in the configuration by using an explicit data type: arcgis vs. postgis vs. mapserver, but I was not able to figure out how to search in a mapserver WMS service.

we have totally separated the viewing part (WMS) and the querying part. We can configure a or ESRI Rest query for any layer, whatever the source is.

**Comment by mki-c2c** [comment]
OK, then this is due to legacy code, which handles the case where neither postgis nor ESRI rest is configured. if you define a rest_url in the config table, the rest API will be used.

I understand that the case pure wms is excluded ?
there are still some layers in this case in the dump we are using for testing:
example: luxemburg_solar_potentials, siden:siden_ouvrages, chargy.

I search for them by using:
```
select geov3.lux_layer_internal_wms.id, url, layers, is_poi 
from geov3.lux_getfeature_definition 
join geov3.lux_layer_internal_wms on geov3.lux_getfeature_definition.layer = geov3.lux_layer_internal_wms.id::text 
where query is null and geov3.lux_getfeature_definition.rest_url is null;
```

**Comment by jaykayone** [comment]
> OK, then this is due to legacy code, which handles the case where neither postgis nor ESRI rest is configured. if you define a rest_url in the config table, the rest API will be used.
> 
> I understand that the case pure wms is excluded ?
> there are still some layers in this case in the dump we are using for testing:
> example: luxemburg_solar_potentials, siden:siden_ouvrages, chargy.
> 
> I search for them by using:
> 
> ```
> select geov3.lux_layer_internal_wms.id, url, layers, is_poi 
> from geov3.lux_getfeature_definition 
> join geov3.lux_layer_internal_wms on geov3.lux_getfeature_definition.layer = geov3.lux_layer_internal_wms.id::text 
> where query is null and geov3.lux_getfeature_definition.rest_url is null;
> ```

OK I see, that's OK for us indeed. If we want to search them we will have to reconfigure the getfeatureinfo definition. 

Great, it's all good then

**Pull request merged**
