### PR TITLE
Upgrade to GeoMapFish master

### PR DESCRIPTION
**Pull request by sbrunner**
La localisation côté serveur doit aussi être corrigée ...

### CODE REVIEW

**Comment by elemoine** [comment]
It looks good to me. Please merge when Travis reports success (which is not the case right now).

**Comment by sbrunner** [comment]
I also update the print :-)

**Comment by elemoine** [comment]
It would be good to know what we (geoportailv3 developers) need to do after a c2cgeoportal upgrade? @sbrunner, would you mind adding a few notes here about that?

**Comment by sbrunner** [comment]
Sauf erreur:
```
make -f <user>.mk update
make -f <user>.mk build
```
Devrai suffire
http://docs.camptocamp.net/c2cgeoportal/master/integrator/upgrade_application.html#easy-updating-an-application-code

**Comment by elemoine** [comment]
Thank you!

**Pull request merged**
