### PR TITLE
Fix jsapi build

### LINKED ISSUE #1785: rebase of jsapi
Hi @fredj 

I want to rebase our jsapi on the master. 
With the ngeo migration I now have the following error. 
I'm not sur how to solve this error. Do you have an idea  ?

> ERR! compile ../../node_modules/ngeo/options/ngeox.js:158: WARNING - Bad type annotation. Unknown type ngeo.rule.Rule
> ERR! compile  * @type {!Array.<!ngeo.rule.Rule>|undefined}
> ERR! compile                    ^
> ERR! compile
> ERR! compile ../../node_modules/ngeo/options/ngeox.js:369: WARNING - Bad type annotation. Unknown type ngeo.DataSource
> ERR! compile  *     dataSources: (Array.<ngeo.DataSource>|undefined),
> ERR! compile                             ^
> ERR! compile
> ERR! compile ../../node_modules/ngeo/options/ngeox.js:394: WARNING - Bad type annotation. Unknown type ngeo.DataSource
> ERR! compile  * @type {Array.<ngeo.DataSource>|undefined}
> ERR! compile                  ^
> ERR! compile
> ERR! compile ../../node_modules/ngeo/options/ngeox.js:465: WARNING - Bad type annotation. Unknown type ngeo.DataSource
> ERR! compile  *     wfs: (!Array.<!ngeo.DataSource>),
> ERR! compile                       ^
> ERR! compile
> ERR! compile ../../node_modules/ngeo/options/ngeox.js:466: WARNING - Bad type annotation. Unknown type ngeo.DataSource
> ERR! compile  *     wms: (!Array.<!ngeo.DataSource>)
> ERR! compile                       ^
> ERR! compile
> ERR! compile ../../node_modules/ngeo/options/ngeox.js:474: WARNING - Bad type annotation. Unknown type ngeo.DataSource
> ERR! compile  * @type {Array.<ngeo.DataSource>}
> ERR! compile                  ^
> ERR! compile
> ERR! compile ../../node_modules/ngeo/options/ngeox.js:481: WARNING - Bad type annotation. Unknown type ngeo.DataSource
> ERR! compile  * @type {Array.<ngeo.DataSource>}
> ERR! compile                  ^
> ERR! compile
> ERR! compile 0 error(s), 7 warning(s), 96.8% typed
> ERR! compile
>

### PR DESCRIPTION
**Pull request by fredj**
Fixes the jsapi build

fixes #1785

### CODE REVIEW

**Comment by rmichaelis** [comment]
Ok. Thanks.
I'll test and merge.

**Comment by fredj** [comment]
it is in conflict with  e7ad684

**Comment by fredj** [comment]
... and I didn't test is the output is correct :-)

**Comment by fredj** [comment]
PLEASE DON'T MERGE, WILL BE FIXED IN NGEO

**Comment by fredj** [comment]
@rmichaelis The issue is now fixed in ngeo, can you test again?

**Comment by rmichaelis** [comment]
LGTM. Thanks.

**Pull request merged**
