### PR TITLE
Fix 486

### PR DESCRIPTION
**Pull request by rmichaelis**
Please review.

### CODE REVIEW

**Comment by pgiraud** [comment]
I see one problem in my browser:
 - you can only hover the text of each item in the dropdown menu,
 - the background doesn't go to the right (only part of the width is highlighted).

screenshot from 2015-06-12 09 29 07

**Comment by rmichaelis** [comment]
Yes you are right. 
There is the same issue in the infobar.

**Comment by rmichaelis** [comment]
Is it better now ?

**Comment by pgiraud** [comment]
It indeeds looks better.
Let's now wait for the travis builds to be fixed before merging.

**Pull request merged**
