### PR TITLE
Set PRINT_OUTPUT to /tmp in elemoine.mk

### PR DESCRIPTION
**Pull request by elemoine**

### CODE REVIEW

**Comment by pgiraud** [comment]
Can you please do the same in my config file? I'll need this too.

**Comment by elemoine** [comment]
> Can you please do the same in my config file? I'll need this too.

Done.

**Comment by pgiraud** [comment]
Please merge, when happy.

**Comment by sbrunner** [comment]
If should also be possible to add the following line:
`DEFAULT_BUILD_RULES = print`
:-)

**Comment by elemoine** [comment]
> If should also be possible to add the following line:
> DEFAULT_BUILD_RULES = print
> :-)

What does that mean exactly?

**Comment by sbrunner** [comment]
The CONST_Makefile build a set of rules that should be run by the build rule, and with DEFAULT_BUILD_RULES we can remove element in the list :-)

**Comment by elemoine** [comment]
> The CONST_Makefile build a set of rules that should be run by the build rule, and with DEFAULT_BUILD_RULES we can remove element in the list :-)

Ok, thanks.

**Pull request merged**
